### ISSUE TITLE
npm install gives many ERR! msgs

### ISSUE THREAD

**Issue by cppljevans** [frankwallis/tower#459]

**Comment by cppljevans** [comment]
I cloned the repo as follows:

```
evansl@lje-DL:~/prog_dev/bridge/github-frankwallis-redouble$ git clone https://github.com/frankwallis/redouble.git
Cloning into 'redouble'...
remote: Enumerating objects: 4496, done.
remote: Total 4496 (delta 0), reused 0 (delta 0), pack-reused 4496
Receiving objects: 100% (4496/4496), 1.02 MiB | 5.24 MiB/s, done.
Resolving deltas: 100% (2709/2709), done.
evansl@lje-DL:~/prog_dev/bridge/github-frankwallis-redouble$
```

Then, several days later followed `npm install` instructions in the README.md:

```
evansl@lje-DL:~/prog_dev/bridge/github-frankwallis-redouble/redouble$ ls
config  LICENSE  package.json  README.md  resources  src
evansl@lje-DL:~/prog_dev/bridge/github-frankwallis-redouble/redouble$ git branch
* master
evansl@lje-DL:~/prog_dev/bridge/github-frankwallis-redouble/redouble$ npm install
npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated co-array@0.0.3: See README.md
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated samsam@1.1.3: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.

> dds-node-adapter@0.1.7 install /home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter
> napa dds-bridge/dds && node-pre-gyp install --fallback-to-build

info git git://github.com/dds-bridge/dds into dds
node-pre-gyp ERR! Tried to download(403): https://dds-node-adapter.s3-eu-west-1.amazonaws.com/dds_node_adapter/v0.1.7/Release/dds_node_adapter-v0.1.7-node-v67-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for dds-node-adapter@0.1.7 and node@11.6.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://dds-node-adapter.s3-eu-west-1.amazonaws.com/dds_node_adapter/v0.1.7/Release/dds_node_adapter-v0.1.7-node-v67-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for dds-node-adapter@0.1.7 and node@11.6.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter/build'
make: Entering directory '/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter/build'
  CXX(target) Release/obj.target/libdds/node_modules/dds/src/dds.o
  CXX(target) Release/obj.target/libdds/node_modules/dds/src/dds.o
rm: cannot remove './Release/.deps/Release/obj.target/libdds/node_modules/dds/src/dds.o.d.raw': No such file or directory
libdds.target.mk:116: recipe for target 'Release/obj.target/libdds/node_modules/dds/src/dds.o' failed
make: *** [Release/obj.target/libdds/node_modules/dds/src/dds.o] Error 1
make: Leaving directory '/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter/build'
  CXX(target) Release/obj.target/libdds/node_modules/dds/src/ABsearch.o
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/evansl/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command "/home/evansl/.nvm/versions/node/v11.6.0/bin/node" "/home/evansl/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter/lib/binding/Release/node-v67-linux-x64/dds_node_adapter.node" "--module_name=dds_node_adapter" "--module_path=/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter/lib/binding/Release/node-v67-linux-x64"
gyp ERR! cwd /home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/evansl/.nvm/versions/node/v11.6.0/bin/node /home/evansl/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter/lib/binding/Release/node-v67-linux-x64/dds_node_adapter.node --module_name=dds_node_adapter --module_path=/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter/lib/binding/Release/node-v67-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Linux 4.15.0-43-generic
node-pre-gyp ERR! command "/home/evansl/.nvm/versions/node/v11.6.0/bin/node" "/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter
node-pre-gyp ERR! node -v v11.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/home/evansl/.nvm/versions/node/v11.6.0/bin/node /home/evansl/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter/lib/binding/Release/node-v67-linux-x64/dds_node_adapter.node --module_name=dds_node_adapter --module_path=/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter/lib/binding/Release/node-v67-linux-x64' (1)
../node_modules/dds/src/ABsearch.cpp:1042:1: fatal error: opening dependency file ./Release/.deps/Release/obj.target/libdds/node_modules/dds/src/ABsearch.o.d.raw: No such file or directory
compilation terminated.
libdds.target.mk:116: recipe for target 'Release/obj.target/libdds/node_modules/dds/src/ABsearch.o' failed
make: *** [Release/obj.target/libdds/node_modules/dds/src/ABsearch.o] Error 1
make: Leaving directory '/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/evansl/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command "/home/evansl/.nvm/versions/node/v11.6.0/bin/node" "/home/evansl/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter/lib/binding/Release/node-v67-linux-x64/dds_node_adapter.node" "--module_name=dds_node_adapter" "--module_path=/home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter/lib/binding/Release/node-v67-linux-x64"
gyp ERR! cwd /home/evansl/prog_dev/bridge/github-frankwallis-redouble/redouble/node_modules/dds-node-adapter
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dds-node-adapter@0.1.7 install: `napa dds-bridge/dds && node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dds-node-adapter@0.1.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/evansl/.npm/_logs/2019-01-08T22_44_44_395Z-debug.log
evansl@lje-DL:~/prog_dev/bridge/github-frankwallis-redouble/redouble$ ls
config  LICENSE  node_modules  package.json  README.md  resources  src
evansl@lje-DL:~/prog_dev/bridge/github-frankwallis-redouble/redouble$
 ```

What am I doing wrong, please?

-regards,
Larry

**Comment by zdraganov** [comment]
Same problem here. @cppljevans did you manage to fix this?

**Comment by frankwallis** [comment]
thanks for raising this, it should be fixed now the version of dds-node-adapter has been updated in master.
